language: objective-c
osx_image: xcode7

before_install:
- export LANG=en_US.UTF-8
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean build -workspace AlamofireOauth2.xcworkspace -scheme Oauth2Test -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO

